import {
  pgTable,
  uuid,
  varchar,
  boolean,
  text,
  integer,
  decimal,
  timestamp,
  date,
  time,
} from 'drizzle-orm/pg-core'

export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).unique().notNull(),
  mobile: varchar('mobile', { length: 15 }).unique().notNull(),
  mobileVerified: boolean('mobile_verified').default(false),
  passwordHash: varchar('password_hash', { length: 255 }),
  fullName: varchar('full_name', { length: 200 }).notNull(),
  role: varchar('role', { length: 20 }).default('customer'),
  preferredLanguage: varchar('preferred_language', { length: 10 }).default('te'),
  createdAt: timestamp('created_at').defaultNow(),
})

export const packages = pgTable('packages', {
  id: uuid('id').primaryKey().defaultRandom(),
  slug: varchar('slug', { length: 200 }).unique().notNull(),
  nameEn: varchar('name_en', { length: 300 }).notNull(),
  nameTe: varchar('name_te', { length: 300 }),
  nameHi: varchar('name_hi', { length: 300 }),
  descriptionEn: text('description_en').notNull(),
  descriptionTe: text('description_te'),
  region: varchar('region', { length: 100 }).notNull(),
  startCity: varchar('start_city', { length: 100 }).notNull(),
  durationDays: integer('duration_days').notNull(),
  durationNights: integer('duration_nights').notNull(),
  pricePerPerson: decimal('price_per_person', { precision: 10, scale: 2 }).notNull(),
  priceChild: decimal('price_child', { precision: 10, scale: 2 }),
  minPersons: integer('min_persons').default(1),
  maxPersons: integer('max_persons').default(50),
  inclusions: text('inclusions').array(),
  exclusions: text('exclusions').array(),
  highlights: text('highlights').array(),
  templesCovered: text('temples_covered').array(),
  coverImageUrl: varchar('cover_image_url', { length: 500 }),
  images: text('images').array(),
  isActive: boolean('is_active').default(true),
  isFeatured: boolean('is_featured').default(false),
  totalBookings: integer('total_bookings').default(0),
  rating: decimal('rating', { precision: 3, scale: 2 }).default('0'),
  createdAt: timestamp('created_at').defaultNow(),
})

export const itineraryDays = pgTable('itinerary_days', {
  id: uuid('id').primaryKey().defaultRandom(),
  packageId: uuid('package_id').references(() => packages.id),
  dayNumber: integer('day_number').notNull(),
  titleEn: varchar('title_en', { length: 300 }).notNull(),
  titleTe: varchar('title_te', { length: 300 }),
  descriptionEn: text('description_en').notNull(),
  descriptionTe: text('description_te'),
  activities: text('activities').array(),
  breakfast: boolean('breakfast').default(false),
  lunch: boolean('lunch').default(false),
  dinner: boolean('dinner').default(false),
  overnightStay: varchar('overnight_stay', { length: 200 }),
  templesVisited: text('temples_visited').array(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const departureDates = pgTable('departure_dates', {
  id: uuid('id').primaryKey().defaultRandom(),
  packageId: uuid('package_id').references(() => packages.id),
  departureDate: date('departure_date').notNull(),
  returnDate: date('return_date').notNull(),
  totalSeats: integer('total_seats').notNull(),
  bookedSeats: integer('booked_seats').default(0),
  priceOverride: decimal('price_override', { precision: 10, scale: 2 }),
  status: varchar('status', { length: 20 }).default('available'),
  notes: varchar('notes', { length: 500 }),
  createdAt: timestamp('created_at').defaultNow(),
})

export const pickupPoints = pgTable('pickup_points', {
  id: uuid('id').primaryKey().defaultRandom(),
  packageId: uuid('package_id').references(() => packages.id),
  city: varchar('city', { length: 100 }).notNull(),
  locationName: varchar('location_name', { length: 200 }).notNull(),
  pickupTime: time('pickup_time').notNull(),
  createdAt: timestamp('created_at').defaultNow(),
})

export const bookings = pgTable('bookings', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingNumber: varchar('booking_number', { length: 20 }).unique().notNull(),
  userId: uuid('user_id').references(() => users.id),
  packageId: uuid('package_id').references(() => packages.id),
  departureDateId: uuid('departure_date_id').references(() => departureDates.id),
  adults: integer('adults').notNull().default(1),
  children: integer('children').default(0),
  pricePerAdult: decimal('price_per_adult', { precision: 10, scale: 2 }).notNull(),
  pricePerChild: decimal('price_per_child', { precision: 10, scale: 2 }).default('0'),
  subtotal: decimal('subtotal', { precision: 10, scale: 2 }).notNull(),
  taxes: decimal('taxes', { precision: 10, scale: 2 }).default('0'),
  totalAmount: decimal('total_amount', { precision: 10, scale: 2 }).notNull(),
  status: varchar('status', { length: 20 }).default('pending'),
  paymentStatus: varchar('payment_status', { length: 20 }).default('pending'),
  razorpayOrderId: varchar('razorpay_order_id', { length: 100 }),
  razorpayPaymentId: varchar('razorpay_payment_id', { length: 100 }),
  contactName: varchar('contact_name', { length: 200 }).notNull(),
  contactMobile: varchar('contact_mobile', { length: 15 }).notNull(),
  contactEmail: varchar('contact_email', { length: 255 }),
  pickupPoint: varchar('pickup_point', { length: 200 }),
  specialRequirements: text('special_requirements'),
  confirmedAt: timestamp('confirmed_at'),
  cancelledAt: timestamp('cancelled_at'),
  createdAt: timestamp('created_at').defaultNow(),
})

export const travellers = pgTable('travellers', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id').references(() => bookings.id),
  fullName: varchar('full_name', { length: 200 }).notNull(),
  age: integer('age').notNull(),
  gender: varchar('gender', { length: 10 }),
  idType: varchar('id_type', { length: 20 }),
  idNumber: varchar('id_number', { length: 50 }),
  isLead: boolean('is_lead').default(false),
  createdAt: timestamp('created_at').defaultNow(),
})

export const reviews = pgTable('reviews', {
  id: uuid('id').primaryKey().defaultRandom(),
  bookingId: uuid('booking_id').references(() => bookings.id).unique(),
  userId: uuid('user_id').references(() => users.id),
  packageId: uuid('package_id').references(() => packages.id),
  rating: integer('rating').notNull(),
  title: varchar('title', { length: 200 }),
  reviewText: text('review_text'),
  images: text('images').array(),
  isVerified: boolean('is_verified').default(true),
  createdAt: timestamp('created_at').defaultNow(),
})

export const enquiries = pgTable('enquiries', {
  id: uuid('id').primaryKey().defaultRandom(),
  packageId: uuid('package_id').references(() => packages.id),
  name: varchar('name', { length: 200 }).notNull(),
  mobile: varchar('mobile', { length: 15 }).notNull(),
  email: varchar('email', { length: 255 }),
  persons: integer('persons').default(1),
  preferredDate: date('preferred_date'),
  message: text('message'),
  status: varchar('status', { length: 20 }).default('new'),
  createdAt: timestamp('created_at').defaultNow(),
})
